ni package.json
ni tsconfig.json
ni .env.example
ni .env
ni src\index.ts
ni src\server.ts
ni src\config.ts
ni src\lib\logger.ts
ni src\lib\errors.ts
ni src\lib\validate.ts
ni src\integrations\notion\notionClient.ts
ni src\integrations\notion\types.ts
ni src\integrations\notion\mapping.ts
ni src\integrations\notion\sync.ts
ni src\integrations\supabase\supabaseClient.ts
ni src\jobs\syncNotionToSupabase.ts
ni src\modules\controlPanel\routes.ts
ni src\modules\tasks\routes.ts
ni src\modules\sops\routes.ts
ni src\modules\crm\routes.ts
ni src\modules\automations\routes.ts
ni db\schema.sql